version: '3.7'

services:
  postgres_local:
    image: postgres:9.6
    ports:
      - '5430:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - PGDATA=/var/lib/postgresql/data/pgdata_local
    logging:
      options:
        max-size: 10m
        max-file: "3"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"

  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    mem_limit: 2048m
    mem_reservation: 128M
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./airflow_jobs:/usr/local/airflow
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow_jobs/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3